In [1]:
inputs = [1, 2, 3, ]
weights = [0.2, 0.8, -0.5]
bias = 2.0

outputs = (inputs[0] * weights[0] + inputs[1] * weights[1] +inputs[2] * weights[2] + bias)

print(outputs)

2.3


Coding second neuron: 4 inputs

In [2]:
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0
outputs = (inputs[0] * weights[0] + inputs[1] 
           * weights[1] +inputs[2] 
           * weights[2] + inputs[3] 
           * weights[3] + bias) 
print(outputs)

4.8


4) Layer of Neurons

In [2]:
inputs = [1, 2, 3, 2.5]
weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

weights1 = weights[0] #List of weights associated with the 1st neuron: w11, w12, w13, w14
weights2 = weights[1] #List of weights associated with the 2nd neuron: w21, w22, w23, w24
weights3 = weights[2] #List of weights associated with the 3rd neuron: w31, w32, w33, w34

biases = [2, 3, 0.5]

bias1 = 2 #Bias associated with the first neuron
bias2 = 3 #Bias associated with the second neuron
bias3 = 0.5 #Bias associated with the third neuron

outputs = [
    # Neuron 1:
    inputs[0]*weights1[0] +
    inputs[1]*weights1[1] +
    inputs[2]*weights1[2] +
    inputs[3]*weights1[3] + bias1,
    # Neuron 2:
    inputs[0]*weights2[0] +
    inputs[1]*weights2[1] +
    inputs[2]*weights2[2] +
    inputs[3]*weights2[3] + bias2,
    # Neuron 3:
    inputs[0]*weights3[0] +
    inputs[1]*weights3[1] +
    inputs[2]*weights3[2] +
    inputs[3]*weights3[3] + bias3
]

print(outputs)


[4.8, 1.21, 2.385]


USING LOOPS FOR BETTER AND EASIER CODING

In [5]:
inputs = [1, 2, 3, 2.5]

##LIST OF WEIGHTS
weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

## LIST OF BIASES
biases = [2, 3, 0.5]

# Create empty layer outputs list to store the outputs of each neuron
layer_outputs = []

# For each neuron
for neuron_weights, neuron_bias in zip(weights, biases):
    # Zeroed output of given neruon
    neuron_output = 0
    # For each input and weight to the neuron
    for n_input, weight in zip(inputs, neuron_weights):
        # Multiply thsi input by associated weight
        # and add to the neuron's output variable
        neuron_output += n_input*weight #e.g. w11*x1 + w12*x2 + w13*x3 + w14*x4
        # Add bias
    neuron_output += neuron_bias # e.g. + b1
    # Put neuron's result to the layer's output list
    layer_outputs.append(neuron_output)

    print(layer_outputs)



[4.8]
[4.8, 1.21]
[4.8, 1.21, 2.385]


USING NUMPY

SINGLE NEURON USING NUMPY

In [7]:
import numpy as np
# Using numpy for matrix operations
inputs = [1, 2, 3, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0
outputs = np.dot(weights, inputs) + bias # dot product of weights and inputs + bias

print(outputs) 

4.8


LAYER OF NEURONS USING NUMPY

In [8]:
## In plain Python, we wrote this as a list of lists. With NumPy, this will be a 2-dimensional array, which we'll call a matrix.

In [11]:
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [
    [0.2, 0.8, -0.5, 1.0],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
]
biases = [2.0, 3.0, 0.5]

# A dot product of a matrix and a vctor results in a list of dot products.
# The np.dot() method treats the matrix as a list of vectors and performs a dot product of each of those vectors with the other vector

layer_outputs = np.dot(weights, inputs) + biases
print(layer_outputs)


[4.8   1.21  2.385]


LAYER OF NEURONS AND BATCH OF DATA USING NUMPY

NEED TO TAKE TRANSPOSE OF WEIGHT MATRIX

In [12]:
inputs = [
    [1.0, 2.0,3.0, 2.5],
    [2.0, 5.0, -1.0, 2.0],
    [-1.5, 2.7, 3.3, -0.8]
]
weights = [
    [0.2, 0.8, -0.5, 1.0],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
]
biases = [2.0, 3.0, 0.5]

# NOTE: WE CAN'T TRANSPOSE LISTS IN PYTHON, SO WE HAVE TO CONVERT THE WEIGHTS MATRIX INTO AN ARRAY FIRST
outputs = np.dot(inputs, np.array(weights).T) + biases
print(outputs)


[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


2 LAYERS AND BATCH OF DATA USING NUMPY

In [3]:
import numpy as np

inputs = [[1, 2, 3, 2.5],
          [2, 5, -1, 2], 
          [-1.5, 2.7, 3.3, -0.8]]

weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]
weights2 = [[0.1, -0.14, 0.5],
            [-0.5, 0.12, -0.33],
            [-0.44, 0.73, -0.13]]
biases2 = [-1, 2, -0.5]
weights3 = [[0.2, 0.8, -0.5],
            [0.5, -0.91, 0.26],
            [-0.26, -0.27, 0.17]]
biases3 = [1.5, 2.5, 0.5]

# Convert lists to numpy arrays
inputs_array = np.array(inputs)
weights_array = np.array(weights)
biases_array = np.array(biases)
weights2_array = np.array(weights2)
biases2_array = np.array(biases2)
weights3_array = np.array(weights3)
biases3_array = np.array(biases3)

# Calculate the output of the first layer
layer1_outputs = np.dot(inputs_array, weights_array.T) + biases_array

# Calculate the output of the second layer
layer2_outputs = np.dot(layer1_outputs, weights2_array.T) + biases2_array

# Calculate the output of the 3rd layer
layer3_outputs = np.dot(layer2_outputs, weights3_array.T) + biases3_array


print(layer2_outputs)
print(layer3_outputs)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]
[[1.786515  3.1695585 0.303906 ]
 [2.24377   3.610454  0.194919 ]
 [2.609679  0.6253156 0.3162171]]
